ordermanager/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from . import views

app_name = 'api'

router_v1 = DefaultRouter()
router_v1.register(
    'orders', views.OrderListRetrieveUpdateViewSet, basename='orders')

urlpatterns = [
    path('v1/', include(router_v1.urls)),
]

ordermanager/ordermanager/urls.py
from django.conf.urls import (  # noqa
    handler400, handler403, handler404, handler500
)
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path

handler400 = 'ordermanager.views.bad_request'  # noqa
handler403 = 'ordermanager.views.permission_denied'  # noqa
handler404 = 'ordermanager.views.page_not_found'  # noqa
handler500 = 'ordermanager.views.server_error'  # noqa

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('api/', include('api.urls', namespace='api')),
    path('', include('orders.urls', namespace='orders')),
]

ordermanager/orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('services/<int:service_id>/order/', views.OrderCreateView.as_view(),
         name='order_create'),
    path('services/', views.ServiceListView.as_view(), name='service_list'),
    path('orders/<int:pk>/complete', views.OrderCompleteView.as_view(),
         name='order_complete'),
    path('orders/<int:pk>/', views.OrderDetailView.as_view(),
         name='order_detail'),
    path('orders/', views.OrderListView.as_view(), name='order_list'),
    path('', views.RouteView.as_view(), name='index'),
]

ordermanager/orders/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Parameter(models.Model):
    title = models.CharField(
        max_length=200, unique=True, verbose_name='Наименование',
        help_text='Наименование параметра услуги')

    class Meta:
        ordering = ['title']
        verbose_name = 'Параметр услуги'
        verbose_name_plural = 'Параметры услуг'

    def __str__(self):
        return self.title


class Service(models.Model):
    title = models.CharField(
        max_length=200, unique=True, verbose_name='Наименование',
        help_text='Наименование услуги')

    class Meta:
        ordering = ['title']
        verbose_name = 'Услуга'
        verbose_name_plural = 'Услуги'

    def __str__(self):
        return self.title


class ParameterInService(models.Model):
    TYPE_CHOICES = [
        ('checkbox', 'Чекбокс'),
        ('text', 'Текст'),
        ('number', 'Целое число'),
    ]
    service = models.ForeignKey(
        Service, models.CASCADE, related_name='parameters_assigned',
        verbose_name='Услуга', help_text='Услуга, для которой задан параметр')
    parameter = models.ForeignKey(
        Parameter, models.CASCADE,
        related_name='services_assigned', verbose_name='Параметр',
        help_text='Параметр, который задан для услуги')
    type = models.CharField(
        max_length=len(max(TYPE_CHOICES, key=lambda x: len(x[0]))[0]),
        choices=TYPE_CHOICES, verbose_name='Тип', help_text='Тип поля формы')

    class Meta:
        ordering = ['type', 'parameter']
        verbose_name = 'Тип параметра для услуги'
        verbose_name_plural = 'Типы параметров для услуг'
        constraints = [
            models.UniqueConstraint(
                fields=['service', 'parameter'],
                name='unique_parameter_in_service',
            ),
        ]

    def __str__(self):
        return (
            f'Для услуги "{self.service}" задан параметр "{self.parameter}" '
            f'с типом "{self.type}"')


class Order(models.Model):
    author = models.ForeignKey(
        User, models.SET_NULL, null=True, related_name='orders_issued',
        verbose_name='Автор', help_text='Автор заказа',
        limit_choices_to=models.Q(is_staff=False))
    service = models.ForeignKey(
        Service, models.CASCADE, related_name='orders', verbose_name='Услуга',
        help_text='Заказываемая услуга')
    time_created = models.DateTimeField(auto_now_add=True, db_index=True)
    complete = models.BooleanField(
        verbose_name='Выполнено', default=False, db_index=True)
    performer = models.ForeignKey(
        User, models.SET_NULL, null=True, related_name='orders_performed',
        verbose_name='Исполнитель', help_text='Исполнитель заказа',
        limit_choices_to=models.Q(is_staff=True))

    class Meta:
        ordering = ['time_created']
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return f'Заказ #{self.id} {self.service.title}'


class ParameterInOrder(models.Model):
    order = models.ForeignKey(
        Order, models.CASCADE,
        related_name='parameters_assigned', verbose_name='Заказ',
        help_text='Заказ, в котором задан параметр услуги')
    parameter = models.ForeignKey(
        Parameter, models.CASCADE,
        related_name='orders_assigned', verbose_name='Параметр',
        help_text='Параметр услуги, который задан в заказе')
    value = models.TextField(
        max_length=2000, verbose_name='Значение',
        help_text='Значение параметра услуги в заказе')

    class Meta:
        verbose_name = 'Параметр услуги в заказе'
        verbose_name_plural = 'Параметры услуг в заказах'
        constraints = [
            models.UniqueConstraint(
                fields=['order', 'parameter'],
                name='unique_parameter_in_order',
            ),
        ]

    def __str__(self):
        return f'Параметр {self.parameter} в заказе {str(self.order)[6:]}'

ordermanager/orders/forms.py
from django import forms
from django.db import transaction
from django.shortcuts import get_object_or_404

from .models import Order, ParameterInOrder, Parameter


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['service']

    def __init__(self, data=None, **kwargs):
        self.parameters = None

        if data is not None:
            self.parameters_in_service = dict()
            for q in range(int(data.get('parameters_quantity', 0))):
                title = data[f'parameter_title_{q}']
                value = data[f'parameter_value_{q}']
                self.parameters_in_service[title] = value

        super().__init__(data=data, **kwargs)

    @transaction.atomic
    def save(self, commit=True):
        order = super().save(commit=False)
        order.save()

        parameters_in_order = []
        for title, value in self.parameters_in_service.items():
            parameter = get_object_or_404(Parameter, title=title)
            parameters_in_order.append(
                ParameterInOrder(
                    order=order, parameter=parameter, value=value))
        ParameterInOrder.objects.bulk_create(parameters_in_order)

        self.save_m2m()
        return order


class OrderCompleteForm(forms.ModelForm):
    class Meta:
        fields = ['performer', 'complete']
        model = Order

ordermanager/orders/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, reverse
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView, DetailView, ListView, RedirectView, UpdateView,
)

from .forms import OrderCompleteForm, OrderCreateForm
from .mixins import IsNotStaffPermissionMixin, IsStaffPermissionMixin
from .models import Order, Service


class ServiceListView(IsNotStaffPermissionMixin, ListView):
    """Display list of services."""
    model = Service


class OrderCreateView(IsNotStaffPermissionMixin, CreateView):
    """Create new orders."""

    success_url = reverse_lazy('orders:index')
    form_class = OrderCreateForm
    model = Order

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        service = get_object_or_404(Service, id=self.kwargs['service_id'])
        context['service'] = service
        context['parameters_in_service'] = (
            service.parameters_assigned.select_related('parameter'))
        return context

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class OrderListView(IsStaffPermissionMixin, ListView):
    """Display list of orders that have not been done yet."""
    queryset = Order.objects.filter(complete=False).select_related('service')


class OrderDetailView(IsStaffPermissionMixin, DetailView):
    """Display details of an order."""
    model = Order


class OrderCompleteView(IsStaffPermissionMixin, UpdateView):
    """Complete an order."""
    form_class = OrderCompleteForm
    model = Order

    def post(self, request, *args, **kwargs):
        super().post(request, *args, **kwargs)

        if self.object.complete is not True:
            self.object.complete = True
            self.object.performer = self.request.user
            self.object.save()

        return HttpResponseRedirect(
            reverse('orders:order_detail', kwargs={'pk': self.object.id}))


class RouteView(LoginRequiredMixin, RedirectView):
    """Redirect staff and non-staff users to different pages."""

    def get_redirect_url(self, *args, **kwargs):
        if self.request.user.is_staff:
            return reverse('orders:order_list')
        return reverse('orders:service_list')

ordermanager/templates/orders/order_create_success.html
{% extends 'base.html' %}
{% block title %}Заказ успешно создан{% endblock %}
{% block content %}
  <h1>Заказ успешно создан</h1>
  <p><a href="{% url 'orders:index' %}">Вернуться на главную страницу</a></p>
{% endblock %}

ordermanager/templates/orders/order_detail.html
{% extends 'base.html' %}
{% block title %}{{ order }}{% endblock %}
{% block content %}
  <h1>{{ order }}</h1>
  {% for item in order.parameters_assigned.all %}
    <p>{{ item.parameter }}: {{ item.value }}</p>
  {% endfor %}
  {% if order.complete is not True %}
    <form method="post" action="complete">{% csrf_token %}
      <button type="submit">Завершить заказ</button>
    </form>
  {% else %}
    <h2>Завершено</h2>
  {% endif %}
  <p><a href="{% url 'orders:index' %}">Вернуться на главную страницу</a></p>
{% endblock %}

ordermanager/templates/orders/order_form.html
{% extends 'base.html' %}
{% block title %}Заказать услугу: {{ service }}{% endblock %}
{% block content %}
  <h1>Заказать услугу:</h1>
  <h1>{{ service }}</h1>
  <form method="post">{% csrf_token %}
   <input type="hidden" name="service" value="{{ service.id }}">
   {% for item in parameters_in_service %}
      <input type="hidden" name="parameter_title_{{ forloop.counter0 }}" value="{{ item.parameter.title }}">
      <p>
        <label for="extra_field_{{ item.id }}">{{ item.parameter.title }}</label>
        {% if item.type == 'checkbox' %}
          <input name="parameter_value_{{ forloop.counter0 }}" type="hidden" value="Нет">
        {% endif %}
        <input id="extra_field_{{ item.id }}" name="parameter_value_{{ forloop.counter0 }}" type="{{ item.type }}"
               {% if item.type == "checkbox" %}value="Да"{% else %}autocomplete="off" required{% endif %}>
      </p>
      {% if forloop.last %}
        <input type="hidden" name="parameters_quantity" value="{{ forloop.counter }}">
      {% endif %}
    {% empty %}
      <input type="hidden" name="parameters_quantity" value="0">
      <p>Список параметров пуст.</p>
    {% endfor %}
    {% for error in form.errors %}
      <p style="color: red;">{{ error }}</p>
    {% endfor %}
    <button type="submit">Заказать услугу</button>
  </form>
  <p><a href="{% url 'orders:index' %}">Вернуться на главную страницу</a></p>
{% endblock %}

ordermanager/templates/orders/order_list.html
{% extends 'base.html' %}
{% block title %}Список заказов{% endblock %}
{% block content %}
  <h1>Список заказов</h1>
  {% for order in order_list %}
    <p><a href="{% url 'orders:order_detail' order.id %}">{{ order }}</a></p>
  {% empty %}
    <p>Список заказов пуст.</p>
  {% endfor %}
{% endblock %}

ordermanager/templates/orders/service_list.html
{% extends 'base.html' %}
{% block title %}Список услуг{% endblock %}
{% block content %}
  <h1>Список услуг</h1>
  {% for service in service_list %}
    <p><a href="{% url 'orders:order_create' service.id %}">{{ service }}</a></p>
  {% empty %}
    <p>Список услуг пуст.</p>
  {% endfor %}
{% endblock %}